---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
  namespace: default
spec:
  chart:
    spec:
      chart: prometheus-operator-crds
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: default
      version: 21.0.0
  interval: 30m0s
